[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      # scheme = "https"
      scheme = "http"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

# [certificatesResolvers.lets-encrypt.acme]
#   email = "your_email@your_domain"
#   storage = "acme.json"
#   [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "frontend"

[providers.file]
  filename = "traefik_dynamic.toml"