- name: Restart all services
  hosts: [webservers]
  gather_facts: no
  tasks:
    - name: Restart all services
      community.docker.docker_compose:
        project_name: arclab
        project_src: "~/projects/arc_services/infra"
        state: present
        build: no
        restarted: yes
      register: output

    - ansible.builtin.debug:
        var: output

    - ansible.builtin.assert:
        that:
          - "caddy.arclab_caddy_1.state.running"
          - "postgres.arclab_postgres_1.state.running"
          - "blog.arclab_blog_1.state.running"
          - "ghost.arclab_ghost_1.state.running"
